#!/bin/bash

echo "=== ПРОВЕРКА ФАЙЛА НА СЕРВЕРЕ ==="
echo ""
echo "Выполните на сервере следующие команды:"
echo ""
echo "1. Проверка файла:"
echo "   wc -l /var/www/repro/resources/views/admin/components/image-crop-input.blade.php"
echo ""
echo "2. Проверка содержимого (первые 20 строк):"
echo "   head -20 /var/www/repro/resources/views/admin/components/image-crop-input.blade.php"
echo ""
echo "3. Проверка наличия нового кода:"
echo "   grep -q 'image-crop-container' /var/www/repro/resources/views/admin/components/image-crop-input.blade.php && echo '✅ Новый код найден' || echo '❌ Новый код НЕ найден'"
echo ""
echo "4. Очистка кеша Laravel:"
echo "   cd /var/www/repro"
echo "   php artisan view:clear"
echo "   php artisan cache:clear"
echo "   php artisan config:clear"
echo ""
echo "5. Проверка последнего коммита на сервере:"
echo "   cd /var/www/repro"
echo "   git log --oneline -5"
echo ""
echo "6. Если файл не обновился, выполните вручную:"
echo "   cd /var/www/repro"
echo "   git pull origin master"
echo "   php artisan view:clear"
echo "   php artisan cache:clear"
