#!/bin/bash

echo "=== КОМАНДЫ ДЛЯ ОБНОВЛЕНИЯ НА СЕРВЕРЕ ==="
echo ""
echo "Выполните следующие команды на сервере через SSH:"
echo ""
echo "1. Подключитесь к серверу:"
echo "   ssh root@45.131.41.102"
echo ""
echo "2. Перейдите в директорию проекта:"
echo "   cd /var/www/repro"
echo ""
echo "3. Обновите код из Git:"
echo "   git fetch origin"
echo "   git pull origin master"
echo ""
echo "4. Очистите кеш Laravel:"
echo "   php artisan view:clear"
echo "   php artisan cache:clear"
echo "   php artisan config:clear"
echo "   php artisan route:clear"
echo ""
echo "Или выполните скрипт автоматически:"
echo "   bash /var/www/repro/server-update.sh"
echo ""
echo "=== ТЕКУЩИЙ КОММИТ В ЛОКАЛЬНОМ РЕПОЗИТОРИИ ==="
git log --oneline -1
