#!/bin/bash

echo "=== ОБНОВЛЕНИЕ НА СЕРВЕРЕ (reprobad) ==="
echo ""
echo "Сервер приложения: 45.131.41.102, каталог: /var/www/repro"
echo ""
echo "Один раз на сервере (после git pull с этим репо):"
echo "  chmod +x /var/www/repro/server-update.sh"
echo ""
echo "Дальше при каждом релизе на сервере:"
echo "  ssh root@45.131.41.102"
echo "  cd /var/www/repro"
echo "  bash server-update.sh"
echo ""
echo "Скрипт сам: git pull, composer install, migrate, optimize:clear, optimize, view:cache, перезапуск php-fpm, sitemap."
echo ""
echo "Автоматически после git pull (опционально), один раз:"
echo "  cp deployment/git-hooks/post-merge.example /var/www/repro/.git/hooks/post-merge"
echo "  chmod +x /var/www/repro/.git/hooks/post-merge"
echo ""
echo "GitHub Actions: см. deployment/GITHUB_ACTIONS_DEPLOY_SCRIPT.yml — та же логика через server-update.sh --skip-pull"
echo ""
echo "=== ТЕКУЩИЙ КОММИТ В ЛОКАЛЬНОМ РЕПОЗИТОРИИ ==="
git log --oneline -1
