#!/bin/bash

echo "=== ПОИСК ПРОЕКТА НА СЕРВЕРЕ ==="
echo ""
echo "Выполните на сервере следующие команды для поиска проекта:"
echo ""
echo "1. Поиск директории проекта:"
echo "   find /var/www -name 'artisan' -type f 2>/dev/null"
echo "   find /home -name 'artisan' -type f 2>/dev/null"
echo "   find /opt -name 'artisan' -type f 2>/dev/null"
echo ""
echo "2. Проверка текущей директории проекта (если знаете путь):"
echo "   ls -la /var/www/repro 2>/dev/null || echo 'Директория не найдена'"
echo "   ls -la /var/www/html 2>/dev/null || echo 'Директория не найдена'"
echo "   ls -la ~/repro 2>/dev/null || echo 'Директория не найдена'"
echo ""
echo "3. Поиск файла image-crop-input.blade.php:"
echo "   find /var/www -name 'image-crop-input.blade.php' 2>/dev/null"
echo "   find /home -name 'image-crop-input.blade.php' 2>/dev/null"
echo ""
echo "4. Проверка git репозитория (если найден проект):"
echo "   cd /path/to/project"
echo "   git remote -v"
echo "   git log --oneline -5"
echo "   git status"
