#!/bin/bash

echo "=== ИСПРАВЛЕНИЕ РАСХОЖДЕНИЯ ВЕТОК НА СЕРВЕРЕ ==="
echo ""
echo "Выполните на сервере следующие команды:"
echo ""
echo "1. Проверка текущего состояния:"
echo "   cd /var/www/repro"
echo "   git status"
echo "   git log --oneline -5"
echo ""
echo "2. Проверка что изменилось локально:"
echo "   git diff HEAD origin/master"
echo ""
echo "3. ВАРИАНТ А (рекомендуется): Сохранить локальные изменения и обновить:"
echo "   git stash"
echo "   git pull origin master --no-rebase"
echo "   git stash pop  # если нужно вернуть локальные изменения"
echo ""
echo "4. ВАРИАНТ Б: Жестко перезаписать локальные изменения удаленными:"
echo "   git fetch origin"
echo "   git reset --hard origin/master"
echo "   php artisan view:clear"
echo "   php artisan cache:clear"
echo ""
echo "5. После обновления проверьте файл:"
echo "   ls -la resources/views/admin/components/image-crop-input.blade.php"
echo "   wc -l resources/views/admin/components/image-crop-input.blade.php"
